### ISSUE TITLE
Cannot add cards: model was not found: Basic (and reversed card)

### ISSUE THREAD

**Issue by tzugen** [jrslwlkn/foxi#1]
Hi,

i followed the instruction but I am unable to add any cards to Anki,
the error shown is "model was not found: Basic (and reversed card)"

**Comment by jrslwlkn** [comment]
Hey, sorry I completely missed this open issue until today. It should be fixed now; the patched version is available now: https://addons.mozilla.org/en-US/firefox/addon/foxi
